// City of birth -> 3-letter code used in control numbers (same list as src/db.js in the Electron app)
pub const CITIES: &[(&str, &str)] = &[
    ("ALAMINOS CITY", "ALM"),
    ("ANGELES CITY", "ANG"),
    ("ANTIPOLO CITY", "ANT"),
    ("BACOLOD CITY", "BCD"),
    ("BACOOR CITY", "BAC"),
    ("BAGO CITY", "BGO"),
    ("BAGUIO CITY", "BAG"),
    ("BAIS CITY", "BAI"),
    ("BALANGA CITY", "BLG"),
    ("BALIWAG CITY", "BAL"),
    ("BATAC CITY", "BAT"),
    ("BATANGAS CITY", "BTC"),
    ("BAYAWAN CITY", "BAY"),
    ("BAYBAY CITY", "BBY"),
    ("BAYUGAN CITY", "BYG"),
    ("BIÑAN CITY", "BIN"),
    ("BISLIG CITY", "BIS"),
    ("BOGO CITY", "BOG"),
    ("BORONGAN CITY", "BOR"),
    ("BUTUAN CITY", "BUT"),
    ("CABADBARAN CITY", "CBD"),
    ("CABANATUAN CITY", "CAB"),
    ("CABUYAO CITY", "CBU"),
    ("CADIZ CITY", "CDZ"),
    ("CAGAYAN DE ORO CITY", "CDO"),
    ("CALACA CITY", "CLC"),
    ("CALAMBA CITY", "CAL"),
    ("CALAPAN CITY", "CPM"),
    ("CALBAYOG CITY", "CLB"),
    ("CALOOCAN CITY", "CLN"),
    ("CANDON CITY", "CND"),
    ("CANLAON CITY", "CAN"),
    ("CARCAR CITY", "CAR"),
    ("CARMONA CITY", "CRM"),
    ("CATBALOGAN CITY", "CTB"),
    ("CAUAYAN CITY", "CAU"),
    ("CAVITE CITY", "CVC"),
    ("CEBU CITY", "CEB"),
    ("COTABATO CITY", "CBC"),
    ("DAGUPAN CITY", "DAG"),
    ("DANAO CITY", "DAN"),
    ("DAPITAN CITY", "DPT"),
    ("DASMARIÑAS CITY", "DAS"),
    ("DAVAO CITY", "DVO"),
    ("DIGOS CITY", "DIG"),
    ("DIPOLOG CITY", "DIP"),
    ("DUMAGUETE CITY", "DUM"),
    ("EL SALVADOR CITY", "ESL"),
    ("ESCALANTE CITY", "ESC"),
    ("GAPAN CITY", "GAP"),
    ("GENERAL SANTOS CITY", "GSA"),
    ("GENERAL TRIAS CITY", "TRI"),
    ("GINGOOG CITY", "GIN"),
    ("GUIHULNGAN CITY", "GUI"),
    ("HIMAMAYLAN CITY", "HIM"),
    ("ILAGAN CITY", "ILA"),
    ("ILIGAN CITY", "ILI"),
    ("ILOILO CITY", "ILO"),
    ("IMUS CITY", "IMU"),
    ("IRIGA CITY", "IRI"),
    ("ISABELA CITY", "ISA"),
    ("ISLAND GARDEN CITY OF SAMAL", "IGC"),
    ("KABANKALAN CITY", "KAB"),
    ("KIDAPAWAN CITY", "KID"),
    ("KORONADAL CITY", "KOR"),
    ("LA CARLOTA CITY", "LCA"),
    ("LAMITAN CITY", "LAM"),
    ("LAOAG CITY", "LAO"),
    ("LAPU-LAPU CITY", "LPL"),
    ("LAS PIÑAS CITY", "LAP"),
    ("LEGAZPI CITY", "LEG"),
    ("LIGAO CITY", "LIG"),
    ("LIPA CITY", "LIP"),
    ("LUCENA CITY", "LUC"),
    ("MAASIN CITY", "MSN"),
    ("MABALACAT CITY", "MAB"),
    ("MAKATI CITY", "MKT"),
    ("MALABON CITY", "MLB"),
    ("MALAYBALAY CITY", "MLY"),
    ("MALOLOS CITY", "MLS"),
    ("MANDALUYONG CITY", "MDY"),
    ("MANDAUE CITY", "MAN"),
    ("MANILA CITY", "MNL"),
    ("MARAWI CITY", "MRW"),
    ("MARIKINA CITY", "MKN"),
    ("MASBATE CITY", "MAS"),
    ("MATI CITY", "MAT"),
    ("MEYCAUAYAN CITY", "MEY"),
    ("MUNTINLUPA CITY", "MTP"),
    ("NAGA CITY (CAMARINES SUR)", "NAG"),
    ("NAGA CITY (CEBU)", "NCE"),
    ("NAVOTAS CITY", "NAV"),
    ("OLONGAPO CITY", "OLG"),
    ("ORMOC CITY", "ORM"),
    ("OROQUIETA CITY", "ORQ"),
    ("OZAMIZ CITY", "OZM"),
    ("PAGADIAN CITY", "PAG"),
    ("PALAYAN CITY", "PLY"),
    ("PANABO CITY", "PAN"),
    ("PARAÑAQUE CITY", "PAR"),
    ("PASAY CITY", "PSY"),
    ("PASIG CITY", "PSG"),
    ("PASSI CITY", "PAS"),
    ("PUERTO PRINCESA CITY", "PPE"),
    ("QUEZON CITY", "QZN"),
    ("ROXAS CITY", "ROX"),
    ("SAGAY CITY", "SAG"),
    ("SAN CARLOS CITY (PANGASINAN)", "SNC"),
    ("SAN CARLOS CITY (NEGROS OCCIDENTAL)", "NCO"),
    ("SAN FERNANDO CITY (LA UNION)", "SFL"),
    ("SAN FERNANDO CITY (PAMPANGA)", "SFP"),
    ("SAN JOSE CITY", "SJC"),
    ("SAN JOSE DEL MONTE CITY", "SJM"),
    ("SAN JUAN CITY", "SNJ"),
    ("SAN PABLO CITY", "SNP"),
    ("SAN PEDRO CITY", "SPD"),
    ("SANTA ROSA CITY", "SNR"),
    ("SANTIAGO CITY", "STG"),
    ("SANTO TOMAS CITY", "STO"),
    ("SCIENCE CITY OF MUÑOZ", "SCO"),
    ("SILAY CITY", "SIL"),
    ("SIPALAY CITY", "SIP"),
    ("SORSOGON CITY", "SOR"),
    ("SURIGAO CITY", "SUR"),
    ("TABACO CITY", "TAB"),
    ("TABUK CITY", "TBK"),
    ("TACLOBAN CITY", "TCL"),
    ("TACURONG CITY", "TCR"),
    ("TAGAYTAY CITY", "TGY"),
    ("TAGBILARAN CITY", "TAG"),
    ("TAGUIG CITY", "TGI"),
    ("TAGUM CITY", "TGM"),
    ("TALISAY CITY (CEBU)", "TCE"),
    ("TALISAY CITY (NEGROS OCCIDENTAL)", "TNO"),
    ("TANAUAN CITY", "TAU"),
    ("TANDAG CITY", "TND"),
    ("TANGUB CITY", "TGB"),
    ("TANJAY CITY", "TNJ"),
    ("TARLAC CITY", "TLC"),
    ("TAYABAS CITY", "TAY"),
    ("TOLEDO CITY", "TOL"),
    ("TRECE MARTIRES CITY", "TRE"),
    ("TUGUEGARAO CITY", "TUG"),
    ("URDANETA CITY", "URD"),
    ("VALENCIA CITY", "VAL"),
    ("VALENZUELA CITY", "VLN"),
    ("VICTORIAS CITY", "VIC"),
    ("VIGAN CITY", "VIG"),
    ("ZAMBOANGA CITY", "ZAM"),
];

#[cfg(test)]
mod tests {
    use super::CITIES;
    use std::collections::HashSet;

    // 149 cities as of 2026 (newest: Carmona, Cavite - July 8, 2023). Update this when a new city is created.
    #[test]
    fn every_philippine_city_is_listed_once() {
        assert_eq!(CITIES.len(), 149);
        let names: HashSet<&str> = CITIES.iter().map(|(name, _)| *name).collect();
        assert_eq!(names.len(), CITIES.len(), "a city name is listed twice");
    }

    // Control numbers rely on these: exactly 3 letters A-Z, no digits, and no two cities sharing a code
    #[test]
    fn city_codes_are_three_unique_letters() {
        for (name, code) in CITIES {
            assert!(code.len() == 3 && code.chars().all(|c| c.is_ascii_uppercase()), "{name}: bad code {code:?}");
        }
        let codes: HashSet<&str> = CITIES.iter().map(|(_, code)| *code).collect();
        assert_eq!(codes.len(), CITIES.len(), "two cities share a code");
    }
}
